### PR TITLE
Add a new provider for khard.

### PR DESCRIPTION
**Pull request by richiware**

### CODE REVIEW

**Review by dbeniamine — CHANGES_REQUESTED** [review]
Thanks for the PR, could you do the following fixes : 
+ Change the author to you
+ Remove the echo line 10

**Comment by richiware** [comment]
Done.

**Comment by dbeniamine** [comment]
Thanks for your contribution :+1:

**Comment by dbeniamine** [comment]
Hello,

While I was doing some refactoring, I saw that your code can only complete email. However from what I read `khard` is a full adressbook. For `pc_query` the plugin completes email or full contacts depending on the current position.

I factorized the code so the writer of the provider only has to check the value of `g:VimMailCompleteOnlyMail` to see wether it should provide completion for full contacts or only emails.

Could you update your code to handle full contacts and make another PR ?

David

**Comment by richiware** [comment]
When I changed the autocompletion for khard I tried to maintain the current behaviour, but I didn't find the khard's 
parameters to get a similar output.

I will try again and make a PR.
↪ 2018-07-07 sáb 20:12, David Beniamine <notifications@github.com>:

**Comment by dbeniamine** [comment]
Yes I am also not sure, I tried to look at `khard` interface but did not found much.
From what I understand you can do `khard list`, but I am not sure that either `kard list jo` or `khard list --parsable` works ...

**Pull request merged**
